// ============================================================
// CONTENT DATA — solar.exe — RPG Village
// ============================================================

window.PORTFOLIO_DATA = {
  player: {
    name: "SOLAR",
    class: "FULL-STACK MAGE",
    title: "Lv.12 Code Wanderer",
    location: "SOLAR VILLAGE",
    tagline: "Crafting interfaces that feel like worlds.",
  },

  stats: {
    HP: { cur: 248, max: 248, label: "VITALITY" },
    MP: { cur: 180, max: 220, label: "FOCUS" },
    XP: { cur: 7820, next: 10000, label: "EXP" },
    GOLD: 1342,
  },

  // Signposts along the path
  // 3 signs: about / skills.frontend / skills.backend  (+ guestbook by house door)
  signs: [
    {
      id: "sign-about",
      title: "ABOUT THE TRAVELER",
      sub: "자기소개",
      icon: "♟",
      color: "magenta",
      x: 470, y: 800,
      kind: "about",
      content: {
        heading: "SOLAR · Lv.12 FULL-STACK MAGE",
        lines: [
          "안녕, 모험가여. 나는 SOLAR.",
          "5년차 프론트엔드 개발자 겸 인터랙션 디자이너.",
          "낡은 게임의 손맛을 동시대 인터페이스에 녹이는 일을 좋아함.",
          "지금은 디자인 시스템과 라이브 서비스 UI를 만들고 있다.",
        ],
        meta: [
          { l: "BASE",      v: "SEOUL · KR" },
          { l: "ALIGNMENT", v: "CHAOTIC GOOD" },
          { l: "LANG",      v: "KO / EN / JS" },
          { l: "EMAIL",     v: "solar@dev.kr" },
          { l: "GITHUB",    v: "@solar-dev" },
          { l: "GUILD",     v: "NEXUS LAB" },
        ],
        attributes: {
          STR: 14, INT: 18, DEX: 16, CHA: 15, LUK: 11, WIS: 17,
        },
      },
    },
    {
      id: "sign-frontend",
      title: "FRONTEND CRAFT",
      sub: "기술 스택 · 프론트엔드",
      icon: "✦",
      color: "cyan",
      x: 690, y: 800,
      kind: "skills",
      content: {
        heading: "▶ FRONTEND ARTS",
        intro: "ui와 모션을 다루는 마법서. 손에 익은 도구들.",
        skills: [
          { name: "HTML / CSS",   lvl: "MAX",   desc: "Semantic · a11y · responsive layout" },
          { name: "JavaScript / TS", lvl: "9/10", desc: "TS 4년차 · 함수형 + 타입 안정성" },
          { name: "React",        lvl: "MAX",   desc: "Hooks · Suspense · Server Components" },
          { name: "Motion",       lvl: "8/10",  desc: "Framer Motion · GSAP · pure CSS" },
          { name: "Pixel Art",    lvl: "7/10",  desc: "16x16 · 32x32 도트 · 자체 에디터 제작" },
          { name: "Figma",        lvl: "MAX",   desc: "디자인 시스템 토큰 · Figma↔코드 자동화" },
        ],
      },
    },
    {
      id: "sign-backend",
      title: "BACKEND FORGE",
      sub: "기술 스택 · 백엔드",
      icon: "◈",
      color: "green",
      x: 910, y: 800,
      kind: "skills",
      content: {
        heading: "▶ BACKEND ARTS",
        intro: "서버와 인프라의 망치. 라이브 서비스의 뼈대.",
        skills: [
          { name: "Node.js",      lvl: "8/10",  desc: "Express · Fastify · WebSocket" },
          { name: "PostgreSQL",   lvl: "6/10",  desc: "스키마 · 인덱스 · 8천 DAU 운영" },
          { name: "API Design",   lvl: "8/10",  desc: "REST + GraphQL + tRPC" },
          { name: "Infra / CI",   lvl: "5/10",  desc: "Docker · GitHub Actions · CF Workers" },
          { name: "LLM Ops",      lvl: "3/10",  desc: "학습 중 · 다음 분기 해금 예정", locked: true },
          { name: "Redis",        lvl: "6/10",  desc: "캐싱 · 큐 · 실시간 세션" },
        ],
      },
    },
    {
      id: "sign-quest",
      title: "QUEST BOARD",
      sub: "경력 · 모험 기록",
      icon: "▲",
      color: "yellow",
      x: 1130, y: 800,
      kind: "quests",
      content: {
        heading: "▶ ADVENTURE LOG",
        intro: "지금까지 클리어한 퀘스트 목록.",
        quests: [
          {
            icon: "★",
            title: "Senior Front-end @ NEXUS LAB",
            meta: "2024.03 ~ NOW · LEAD GUILD",
            desc: "디자인 시스템 리드. ECHO TERMINAL 신규 모듈 개발 + 운영.",
            xp: "+ 4,200 XP",
            state: "active",
          },
          {
            icon: "✓",
            title: "Front-end Engineer @ AURORA STUDIO",
            meta: "2022.01 ~ 2024.02 · CRAFT GUILD",
            desc: "B2C 모바일 앱 출시 3건. 모션 시스템 정립.",
            xp: "+ 3,400 XP",
            state: "completed",
          },
          {
            icon: "✓",
            title: "Indie Dev / Designer (Freelance)",
            meta: "2021.04 ~ 2021.12 · SOLO RUN",
            desc: "픽셀 아트 에디터 PIXEL FORGE 출시. 게임잼 4회.",
            xp: "+ 1,200 XP",
            state: "completed",
          },
          {
            icon: "✓",
            title: "B.S. Computer Science @ KAIST",
            meta: "2017 ~ 2021 · ACADEMY ARC",
            desc: "전공 CS, 부전공 시각디자인. 졸업프로젝트로 멀티유저 픽셀 캔버스.",
            xp: "+ 2,000 XP",
            state: "completed",
          },
        ],
      },
    },
  ],

  // House: door position on world map; player walking onto it triggers indoor scene
  house: {
    id: "house",
    title: "SOLAR'S WORKSHOP",
    sub: "프로젝트 갤러리",
    x: 1280, y: 580,
    w: 280, h: 240,
    doorOffsetX: 140,
    doorOffsetY: 240,
  },

  // Project frames inside the house
  projects: [
    {
      id: "p1",
      name: "ECHO TERMINAL",
      type: "WEAPON / Live Tool",
      rarity: "legendary",
      icon: "⚔",
      iconColor: "#ffd84d",
      thumbColor: ["#ffd84d", "#ff9c4d"],
      desc: "팀 전체가 사용하는 로그/메트릭 대시보드. 8천명 DAU. 라이브 서비스 운영 중인 팀의 사이드킥.",
      stats: [["TIER","LEGENDARY"],["DAU","8,200"],["UPTIME","99.97%"],["LOC","42K"]],
      tags: ["React","WebSocket","D3","Postgres","K8s"],
      yr: "2024 ~ NOW",
    },
    {
      id: "p2",
      name: "PIXEL FORGE",
      type: "TOOL / Editor",
      rarity: "epic",
      icon: "✦",
      iconColor: "#b34dff",
      thumbColor: ["#b34dff", "#ff4dd6"],
      desc: "브라우저에서 동작하는 픽셀 아트 에디터. 레이어/팔레트/익스포트까지. 12k stars.",
      stats: [["TIER","EPIC"],["STARS","12,400"],["FORKS","780"],["LANG","TypeScript"]],
      tags: ["Canvas","WASM","OSS"],
      yr: "2023",
    },
    {
      id: "p3",
      name: "QUEST CARDS",
      type: "ARTIFACT / Mobile",
      rarity: "rare",
      icon: "❖",
      iconColor: "#4dd6ff",
      thumbColor: ["#4dd6ff","#4dff8a"],
      desc: "할 일을 RPG 퀘스트로 바꿔주는 모바일 앱. 디자인부터 출시까지 단독 진행.",
      stats: [["TIER","RARE"],["INSTALLS","44K"],["RATING","4.7 ★"],["PLATFORM","iOS/AOS"]],
      tags: ["React Native","Solo","Indie"],
      yr: "2022",
    },
    {
      id: "p4",
      name: "LUMEN UI KIT",
      type: "GRIMOIRE / System",
      rarity: "epic",
      icon: "✧",
      iconColor: "#b34dff",
      thumbColor: ["#b34dff","#4dd6ff"],
      desc: "사내 디자인 시스템. 142개 컴포넌트, 320개 토큰. Figma↔코드 자동 싱크.",
      stats: [["TIER","EPIC"],["TOKENS","320"],["COMP","142"],["TEAMS","11"]],
      tags: ["Storybook","Tokens","CI"],
      yr: "2023 ~ 2024",
    },
    {
      id: "p5",
      name: "RETRO BOSS RUSH",
      type: "GAME / Web",
      rarity: "uncommon",
      icon: "♛",
      iconColor: "#4dff8a",
      thumbColor: ["#4dff8a","#ffd84d"],
      desc: "주말에 만든 보스 러시 미니 게임. 게임잼 출품작. 손맛/이펙트/사운드까지 단독 작업.",
      stats: [["TIER","UNCOMMON"],["JAM RANK","#7 / 320"],["PLAYS","11K"],["DEV TIME","48 hr"]],
      tags: ["Phaser","GameJam","Pixel"],
      yr: "2023",
    },
    {
      id: "p6",
      name: "SCROLL OF DOCS",
      type: "SCROLL / Content",
      rarity: "rare",
      icon: "❀",
      iconColor: "#4dd6ff",
      thumbColor: ["#4dd6ff","#ff6ec7"],
      desc: "프론트엔드 모션 디자인 시리즈 글. 한국어/영어. 누적 조회 90만.",
      stats: [["TIER","RARE"],["VIEWS","910K"],["POSTS","28"],["LANGS","KO / EN"]],
      tags: ["Writing","Motion","Tutorial"],
      yr: "2021 ~ NOW",
    },
  ],
};

window.PORTFOLIO_DATA.projects = [
  {
    id: "repo-oss-project3",
    name: "OSS PROJECT 3",
    type: "Vue / Open Source Project",
    rarity: "legendary",
    icon: "V",
    iconColor: "#4fc08d",
    thumbColor: ["#4fc08d", "#35495e"],
    desc: "A recently updated Vue project from 05solar's public GitHub repositories.",
    stats: [["TIER","LEGENDARY"],["LANG","Vue"],["UPDATED","2026.05"],["SIZE","38.8 MB"]],
    tags: ["Vue","OSS","Frontend","GitHub"],
    yr: "2026",
    url: "https://github.com/05solar/OSS_project3",
  },
  {
    id: "repo-mcp",
    name: "JBNU LAB 3 MCP",
    type: "JavaScript / MCP Lab",
    rarity: "epic",
    icon: "M",
    iconColor: "#f7df1e",
    thumbColor: ["#f7df1e", "#2d1a52"],
    desc: "A JavaScript MCP lab repository for experimenting with tool-connected app workflows.",
    stats: [["TIER","EPIC"],["LANG","JavaScript"],["UPDATED","2026.05"],["SIZE","400 KB"]],
    tags: ["JavaScript","MCP","Lab","Tools"],
    yr: "2026",
    url: "https://github.com/05solar/JBNU-lab3-MCP",
  },
  {
    id: "repo-rag",
    name: "JBNU LAB 2 RAG",
    type: "Python / RAG Lab",
    rarity: "rare",
    icon: "R",
    iconColor: "#4dd6ff",
    thumbColor: ["#4dd6ff","#4dff8a"],
    desc: "A Python RAG lab project exploring retrieval-augmented generation patterns.",
    stats: [["TIER","RARE"],["LANG","Python"],["UPDATED","2026.05"],["TOPIC","RAG"]],
    tags: ["Python","RAG","AI","Lab"],
    yr: "2026",
    url: "https://github.com/05solar/JBNU-lab2-RAG",
  },
  {
    id: "repo-chatbot",
    name: "JBNU LAB 1 CHATBOT",
    type: "JavaScript / Chatbot Lab",
    rarity: "epic",
    icon: "C",
    iconColor: "#ff7acb",
    thumbColor: ["#ff7acb","#7b5cff"],
    desc: "A JavaScript chatbot lab repository focused on conversational UI and app logic.",
    stats: [["TIER","EPIC"],["LANG","JavaScript"],["UPDATED","2026.05"],["TYPE","Chatbot"]],
    tags: ["JavaScript","Chatbot","UI","Lab"],
    yr: "2026",
    url: "https://github.com/05solar/JBNU-lab1-chatbot",
  },
  {
    id: "repo-pharmacy",
    name: "OSS PHARMACY",
    type: "JavaScript / Web App",
    rarity: "uncommon",
    icon: "P",
    iconColor: "#4dff8a",
    thumbColor: ["#4dff8a","#ffd84d"],
    desc: "A JavaScript web app repository with a pharmacy-oriented project theme.",
    stats: [["TIER","UNCOMMON"],["LANG","JavaScript"],["UPDATED","2026"],["TYPE","Web App"]],
    tags: ["JavaScript","Web","OSS","App"],
    yr: "2026",
    url: "https://github.com/05solar/OSS_pharmacy",
  },
  {
    id: "repo-japan-travel",
    name: "JAPAN TRAVEL",
    type: "JavaScript / Travel Site",
    rarity: "rare",
    icon: "J",
    iconColor: "#ff9c4d",
    thumbColor: ["#ff9c4d","#4dd6ff"],
    desc: "A JavaScript travel-themed website project from the public repository list.",
    stats: [["TIER","RARE"],["LANG","JavaScript"],["UPDATED","2025"],["THEME","Travel"]],
    tags: ["JavaScript","Travel","Website","Frontend"],
    yr: "2025",
    url: "https://github.com/05solar/japan-travel",
  },
];
