// ============================================================
// CONTENT DATA - solar.exe RPG portfolio
// ============================================================

window.PORTFOLIO_DATA = {
  player: {
    name: "SOLAR",
    class: "풀스택 메이지",
    title: "Lv.12 코드 여행자",
    location: "솔라 마을",
    tagline: "인터페이스를 하나의 세계처럼 설계합니다.",
  },

  stats: {
    HP: { cur: 248, max: 248, label: "활력" },
    MP: { cur: 180, max: 220, label: "집중력" },
    XP: { cur: 7820, next: 10000, label: "경험치" },
    GOLD: 1342,
  },

  signs: [
    {
      id: "sign-about",
      title: "여행자 소개",
      sub: "자기소개",
      icon: "i",
      color: "magenta",
      x: 470, y: 800,
      kind: "about",
      content: {
        heading: "SOLAR - Lv.12 풀스택 메이지",
        lines: [
          "안녕하세요. 게임처럼 탐험하는 포트폴리오를 만든 SOLAR입니다.",
          "프론트엔드와 백엔드를 함께 다루며, 사용자가 길을 잃지 않는 인터페이스를 좋아합니다.",
          "작은 상호작용, 명확한 정보 구조, 오래 봐도 피곤하지 않은 화면을 중요하게 생각합니다.",
          "현재는 React 기반 웹앱, 챗봇, RAG 실험, 오픈소스 과제를 중심으로 작업하고 있습니다.",
        ],
        meta: [
          { l: "거점",      v: "전주 / 대한민국" },
          { l: "성향",      v: "호기심 많은 제작자" },
          { l: "언어",      v: "한국어 / 영어 / JavaScript" },
          { l: "이메일",    v: "solar@dev.kr" },
          { l: "깃허브",    v: "@05solar" },
          { l: "길드",      v: "JBNU LAB" },
        ],
        attributes: {
          STR: 14, INT: 18, DEX: 16, CHA: 15, LUK: 11, WIS: 17,
        },
      },
    },
    {
      id: "sign-frontend",
      title: "프론트엔드 제작",
      sub: "기술 스택 - 프론트엔드",
      icon: "F",
      color: "cyan",
      x: 690, y: 800,
      kind: "skills",
      content: {
        heading: "프론트엔드 기술",
        intro: "화면 구조, 상태 관리, 반응형 UI, 작은 움직임까지 사용 흐름에 맞춰 설계합니다.",
        skills: [
          { name: "HTML / CSS", lvl: "MAX", desc: "시맨틱 마크업, 접근성, 반응형 레이아웃" },
          { name: "JavaScript / TS", lvl: "9/10", desc: "명확한 상태 흐름과 안정적인 타입 설계" },
          { name: "React", lvl: "MAX", desc: "Hooks, 컴포넌트 설계, Vite 기반 앱 구성" },
          { name: "Motion", lvl: "8/10", desc: "CSS 애니메이션과 화면 전환 연출" },
          { name: "Pixel UI", lvl: "7/10", desc: "게임풍 UI, HUD, 모달, 작은 인터랙션 제작" },
          { name: "Figma", lvl: "8/10", desc: "화면 설계, 컴포넌트 정리, 디자인 토큰" },
        ],
      },
    },
    {
      id: "sign-backend",
      title: "백엔드 작업대",
      sub: "기술 스택 - 백엔드",
      icon: "B",
      color: "green",
      x: 910, y: 800,
      kind: "skills",
      content: {
        heading: "백엔드 기술",
        intro: "데이터 흐름과 API 구조를 정리하고, 프론트엔드가 쓰기 편한 서버를 만듭니다.",
        skills: [
          { name: "Node.js", lvl: "8/10", desc: "Express, API 서버, 실시간 통신 기본기" },
          { name: "Python", lvl: "7/10", desc: "RAG 실험, 데이터 처리, 챗봇 프로토타입" },
          { name: "API Design", lvl: "8/10", desc: "REST API, 요청/응답 구조, 에러 처리" },
          { name: "Database", lvl: "6/10", desc: "스키마 설계, 쿼리 작성, 데이터 모델링" },
          { name: "LLM / RAG", lvl: "6/10", desc: "검색 증강 생성, 프롬프트 설계, 도구 연결" },
          { name: "DevOps", lvl: "5/10", desc: "Vite 빌드, 배포 준비, GitHub 워크플로" },
        ],
      },
    },
    {
      id: "sign-quest",
      title: "퀘스트 게시판",
      sub: "경력과 작업 기록",
      icon: "Q",
      color: "yellow",
      x: 1130, y: 800,
      kind: "quests",
      content: {
        heading: "모험 기록",
        intro: "지금까지 완료했거나 진행 중인 개발 퀘스트입니다.",
        quests: [
          {
            icon: "01",
            title: "OSS PROJECT 3",
            meta: "2026.05 - Vue 오픈소스 프로젝트",
            desc: "Vue 기반 공개 저장소를 정리하고, 프론트엔드 구조와 프로젝트 문서를 개선했습니다.",
            xp: "+ 4,200 XP",
            state: "active",
          },
          {
            icon: "02",
            title: "JBNU LAB 3 MCP",
            meta: "2026.05 - JavaScript MCP 실험",
            desc: "도구 연결형 앱 워크플로와 MCP 구조를 실험한 JavaScript 프로젝트입니다.",
            xp: "+ 3,400 XP",
            state: "completed",
          },
          {
            icon: "03",
            title: "JBNU LAB 2 RAG",
            meta: "2026.05 - Python RAG 실험",
            desc: "검색 증강 생성 패턴을 테스트하며 문서 검색과 답변 생성을 연결했습니다.",
            xp: "+ 2,000 XP",
            state: "completed",
          },
          {
            icon: "04",
            title: "JBNU LAB 1 CHATBOT",
            meta: "2026.05 - 챗봇 UI 실험",
            desc: "대화형 UI와 앱 로직을 중심으로 챗봇 프로젝트를 구현했습니다.",
            xp: "+ 1,200 XP",
            state: "completed",
          },
        ],
      },
    },
  ],

  house: {
    id: "house",
    title: "SOLAR 작업실",
    sub: "프로젝트 갤러리",
    x: 1280, y: 580,
    w: 280, h: 240,
    doorOffsetX: 140,
    doorOffsetY: 240,
  },

  projects: [
    {
      id: "repo-oss-project3",
      name: "OSS PROJECT 3",
      type: "Vue / 오픈소스 프로젝트",
      rarity: "legendary",
      icon: "V",
      iconColor: "#4fc08d",
      thumbColor: ["#4fc08d", "#35495e"],
      desc: "05solar의 공개 GitHub 저장소 중 최근 업데이트된 Vue 프로젝트입니다. 프론트엔드 구조와 오픈소스 과제 흐름을 확인할 수 있습니다.",
      stats: [["등급","전설"],["언어","Vue"],["업데이트","2026.05"],["크기","38.8 MB"]],
      tags: ["Vue","OSS","Frontend","GitHub"],
      yr: "2026",
      url: "https://github.com/05solar/OSS_project3",
    },
    {
      id: "repo-mcp",
      name: "JBNU LAB 3 MCP",
      type: "JavaScript / MCP 실험",
      rarity: "epic",
      icon: "M",
      iconColor: "#f7df1e",
      thumbColor: ["#f7df1e", "#2d1a52"],
      desc: "도구와 연결되는 앱 워크플로를 실험한 JavaScript MCP 랩 프로젝트입니다.",
      stats: [["등급","영웅"],["언어","JavaScript"],["업데이트","2026.05"],["크기","400 KB"]],
      tags: ["JavaScript","MCP","Lab","Tools"],
      yr: "2026",
      url: "https://github.com/05solar/JBNU-lab3-MCP",
    },
    {
      id: "repo-rag",
      name: "JBNU LAB 2 RAG",
      type: "Python / RAG 실험",
      rarity: "rare",
      icon: "R",
      iconColor: "#4dd6ff",
      thumbColor: ["#4dd6ff","#4dff8a"],
      desc: "검색 증강 생성 구조를 익히기 위해 만든 Python RAG 실험 프로젝트입니다.",
      stats: [["등급","희귀"],["언어","Python"],["업데이트","2026.05"],["주제","RAG"]],
      tags: ["Python","RAG","AI","Lab"],
      yr: "2026",
      url: "https://github.com/05solar/JBNU-lab2-RAG",
    },
    {
      id: "repo-chatbot",
      name: "JBNU LAB 1 CHATBOT",
      type: "JavaScript / 챗봇 실험",
      rarity: "epic",
      icon: "C",
      iconColor: "#ff7acb",
      thumbColor: ["#ff7acb","#7b5cff"],
      desc: "대화형 UI와 앱 로직을 중심으로 구성한 JavaScript 챗봇 랩 프로젝트입니다.",
      stats: [["등급","영웅"],["언어","JavaScript"],["업데이트","2026.05"],["유형","Chatbot"]],
      tags: ["JavaScript","Chatbot","UI","Lab"],
      yr: "2026",
      url: "https://github.com/05solar/JBNU-lab1-chatbot",
    },
    {
      id: "repo-pharmacy",
      name: "OSS PHARMACY",
      type: "JavaScript / 웹 앱",
      rarity: "uncommon",
      icon: "P",
      iconColor: "#4dff8a",
      thumbColor: ["#4dff8a","#ffd84d"],
      desc: "약국 서비스를 주제로 만든 JavaScript 웹 앱 프로젝트입니다.",
      stats: [["등급","고급"],["언어","JavaScript"],["업데이트","2026"],["유형","Web App"]],
      tags: ["JavaScript","Web","OSS","App"],
      yr: "2026",
      url: "https://github.com/05solar/OSS_pharmacy",
    },
    {
      id: "repo-japan-travel",
      name: "JAPAN TRAVEL",
      type: "JavaScript / 여행 사이트",
      rarity: "rare",
      icon: "J",
      iconColor: "#ff9c4d",
      thumbColor: ["#ff9c4d","#4dd6ff"],
      desc: "일본 여행을 주제로 제작한 JavaScript 웹사이트 프로젝트입니다.",
      stats: [["등급","희귀"],["언어","JavaScript"],["업데이트","2025"],["주제","Travel"]],
      tags: ["JavaScript","Travel","Website","Frontend"],
      yr: "2025",
      url: "https://github.com/05solar/japan-travel",
    },
  ],
};
